/**
 * Build the OpenAI submission package from ritmo.yaml (+ live tool
 * descriptors when a server is reachable). Pure: returns file contents,
 * the command writes them. See docs/apps-sdk-contract.md §8 for what the
 * portal form asks for.
 */

import yaml from 'js-yaml'

import type {AppRhythmConfig} from '../config-schema.js'
import type {RawTool} from '../mcp/client.js'
import {annotationsOf} from '../validate/meta.js'

export interface PackageInput {
  config: AppRhythmConfig
  /** Raw tool descriptors from the server, if it was reachable. */
  tools?: RawTool[]
  /** Server URL the tools came from (for the README). */
  serverUrl: string
  /** ISO timestamp for the manifest header. */
  generatedAt: string
}

export interface PackageFile {
  /** Relative path inside the output directory. */
  path: string
  content: string
}

export interface PackageOutput {
  files: PackageFile[]
  /** Human-readable notes about what's missing (mirrors validate's submission/* rules loosely). */
  notes: string[]
}

export function buildSubmissionPackage(input: PackageInput): PackageOutput {
  const {config, tools, serverUrl, generatedAt} = input
  const sub = config.submission ?? {
    showcase_prompts: [], test_cases: [], negative_test_cases: [], tools: {}, skills: [], country_availability: [],
  }
  const app = config.app
  const notes: string[] = []

  // ---- listing.md ---------------------------------------------------------
  const listing = [
    `# ${app.name}`,
    '',
    `Generated by \`ritmo package\` on ${generatedAt} from project configuration (server: ${serverUrl}).`,
    'Copy each field into the OpenAI submission portal.',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Name (≤ 30) | ${app.name} (${app.name.length}) |`,
    `| Subtitle (≤ 30) | ${app.subtitle ?? '_missing_'}${app.subtitle ? ` (${app.subtitle.length})` : ''} |`,
    `| Icon | ${app.icon} |`,
    `| Privacy policy URL | ${app.privacy_policy_url ?? '_missing_'} |`,
    `| Terms URL | ${app.terms_url ?? '_missing_'} |`,
    `| Company URL | ${app.company_url ?? '_missing_'} |`,
    `| Support URL | ${app.support_url ?? '_missing_'} |`,
    `| Screenshots | ${app.screenshots.length ? app.screenshots.join(', ') : '_none_'} |`,
    '',
    '## Description',
    '',
    app.description,
    '',
    '## Showcase prompts',
    '',
    ...(sub.showcase_prompts.length
      ? sub.showcase_prompts.map((p, i) => `${i + 1}. ${p}`)
      : ['_none configured — add submission.showcase_prompts_']),
    '',
  ]
  if (!app.subtitle) notes.push('app.subtitle missing')
  if (!app.privacy_policy_url) notes.push('app.privacy_policy_url missing')
  if (!app.terms_url) notes.push('app.terms_url missing')
  if (sub.showcase_prompts.length === 0) notes.push('no showcase prompts')

  // ---- test-cases.md ------------------------------------------------------
  const tc = [
    '# Test cases',
    '',
    `## Positive (${sub.test_cases.length}; portal requires ≥ 5)`,
    '',
    ...sub.test_cases.flatMap((t, i) => [
      `### ${i + 1}. ${t.scenario}`,
      '',
      `- **Prompt:** ${t.prompt}`,
      `- **Tools triggered:** ${t.tools.join(', ')}`,
      `- **Expected result:** ${t.expected}`,
      ...(t.fixture ? [`- **Fixture / test account:** ${t.fixture}`] : []),
      '',
    ]),
    `## Negative (${sub.negative_test_cases.length}; portal requires ≥ 3)`,
    '',
    ...sub.negative_test_cases.flatMap((t, i) => [
      `### ${i + 1}. ${t.scenario}`,
      '',
      `- **Prompt:** ${t.prompt}`,
      `- **Expected behaviour:** app must NOT trigger`,
      `- **Rationale:** ${t.rationale}`,
      '',
    ]),
  ]
  if (sub.test_cases.length < 5) notes.push(`${sub.test_cases.length}/5 positive test cases`)
  if (sub.negative_test_cases.length < 3) notes.push(`${sub.negative_test_cases.length}/3 negative test cases`)

  // ---- skills.md ----------------------------------------------------------
  const skills = [
    '# Skills',
    '',
    'Ritmo records the exact local skill tree that was tested. It does not execute or security-scan skill code; OpenAI scans the uploaded or MCP-imported snapshot during submission.',
    '',
    '| Skill | Delivery | Local source tree |',
    '|---|---|---|',
    ...(sub.skills.length
      ? sub.skills.map((skill) => `| ${skill.name} | ${skill.delivery} | ${skill.path} |`)
      : ['| _No skills configured_ | MCP-only plugin | — |']),
    '',
  ]

  // ---- global.md ----------------------------------------------------------
  const global = [
    '# Global availability and policy attestations',
    '',
    '## Country availability',
    '',
    sub.country_availability.length
      ? sub.country_availability.join(', ')
      : '_missing — select only locations where the publisher, product, support process, and legal terms are ready._',
    '',
    '## Policy attestations',
    '',
    `- **Confirmed:** ${sub.policy_attestations?.confirmed ? 'yes' : 'no'}`,
    `- **Confirmed by:** ${sub.policy_attestations?.confirmed_by ?? '_missing_'}`,
    `- **Confirmed at:** ${sub.policy_attestations?.confirmed_at ?? '_missing_'}`,
    '',
    'This record documents a human portal action. It is not a guarantee that a plugin complies with OpenAI policy or will be approved.',
    '',
  ]
  if (sub.country_availability.length === 0) notes.push('no country availability')
  if (!sub.policy_attestations?.confirmed) notes.push('policy attestations not confirmed')

  // ---- release-notes.md ---------------------------------------------------
  const releaseNotes = sub.release_notes
  const release = releaseNotes
    ? [
      '# Release notes',
      '',
      `- **Submission:** ${releaseNotes.kind}`,
      '',
      '## Summary',
      '',
      releaseNotes.summary,
      '',
      '## Changes since prior submission',
      '',
      releaseNotes.changes,
      '',
      '## Reviewer setup notes',
      '',
      releaseNotes.reviewer_notes,
      '',
    ]
    : ['# Release notes', '', '_missing — state what the plugin does, whether this is initial or an update, what changed, and reviewer setup notes._', '']
  if (!releaseNotes) notes.push('release notes missing')

  // ---- annotations.md -----------------------------------------------------
  const ann: string[] = ['# Tool annotations + justifications', '']
  if (!tools) {
    ann.push('_Server was not reachable; listing tools from submission.tools only._', '')
    notes.push('server unreachable — annotations table built from config only')
  }
  const toolNames = tools ? tools.map((t) => t.name) : Object.keys(sub.tools)
  ann.push('| Tool | readOnlyHint | destructiveHint | openWorldHint |', '|---|---|---|---|')
  for (const name of toolNames) {
    const raw = tools?.find((t) => t.name === name)
    const a = raw ? annotationsOf(raw) : {}
    const j = sub.tools[name]?.justifications ?? {}
    const cell = (k: 'readOnlyHint' | 'destructiveHint' | 'openWorldHint') => {
      const v = typeof a[k] === 'boolean' ? String(a[k]) : '?'
      return `${v} — ${j[k] ?? '_no justification_'}`
    }
    ann.push(`| ${name} | ${cell('readOnlyHint')} | ${cell('destructiveHint')} | ${cell('openWorldHint')} |`)
    if (!j.readOnlyHint || !j.destructiveHint || !j.openWorldHint) notes.push(`${name}: incomplete justifications`)
  }
  ann.push('')

  // ---- tests/submission.yaml (runnable with `ritmo test`) ---------------
  const suite = {
    suite: `${app.name} — submission test cases`,
    tests: [
      ...sub.test_cases.map((t) => ({
        name: `positive: ${t.scenario}`,
        user: t.prompt,
        expect_tool: t.tools[0],
      })),
      ...sub.negative_test_cases.map((t) => ({
        name: `negative: ${t.scenario}`,
        user: t.prompt,
        expect_no_tool_call: true,
      })),
    ],
  }

  // ---- submission.json (machine-readable everything) -----------------------
  const json = {
    generatedAt,
    serverUrl,
    app,
    submission: sub,
    tools: (tools ?? []).map((t) => ({
      name: t.name,
      title: t.title,
      description: t.description,
      annotations: annotationsOf(t),
      justifications: sub.tools[t.name]?.justifications ?? {},
    })),
  }

  const files: PackageFile[] = [
    {path: 'listing.md', content: listing.join('\n')},
    {path: 'test-cases.md', content: tc.join('\n')},
    {path: 'annotations.md', content: ann.join('\n')},
    {path: 'skills.md', content: skills.join('\n')},
    {path: 'global.md', content: global.join('\n')},
    {path: 'release-notes.md', content: release.join('\n')},
    {path: 'submission.json', content: JSON.stringify(json, null, 2) + '\n'},
  ]
  if (suite.tests.length > 0) {
    files.push({path: 'tests/submission.yaml', content: yaml.dump(suite, {lineWidth: 120})})
  }

  return {files, notes}
}
